package com.cc.cenntrum.utils

import com.cc.cenntrum.R

object Constants {

    const val BASE_URL: String =
        "https://www.geeksforgeeks.org/data-binding-in-android-with-example/"
    const val TAG: String = "TAG"
    const val ARG_PARAM1 = "param1"
    const val ARG_PARAM2 = "param2"
    const val ARG_PARAM3 = "param3"
    const val ARG_PARAM4 = "param4"
    const val ARG_PARAM5 = "param5"
    const val ARG_PARAM6 = "param6"
    const val ARG_PARAM7 = "param7"
    const val ARG_PARAM8 = "param8"
    const val MY_PERMISSIONS_REQUEST_LOCATION = 99
    const val COINS_DELAY_TIME: Long = 30000
    val REQUEST_GPS = 199

     val imgMap: Map<Int, Int> = mapOf(
        1 to R.drawable.img1,
        2 to R.drawable.img2,
        3 to R.drawable.img3,
        4 to R.drawable.img4,
        5 to R.drawable.img5,
        6 to R.drawable.img6,
        7 to R.drawable.img7,
        8 to R.drawable.img8,
        9 to R.drawable.img9,
        10 to R.drawable.img10,
        11 to R.drawable.img11,
        12 to R.drawable.img12,
        13 to R.drawable.img13,
        14 to R.drawable.img14,
        15 to R.drawable.img15,
        16 to R.drawable.img16,
        17 to R.drawable.img17,
        18 to R.drawable.img18,
        19 to R.drawable.img19,
        20 to R.drawable.img20,
        21 to R.drawable.img21,
        22 to R.drawable.img22,
        23 to R.drawable.img23,
        24 to R.drawable.img24,
        25 to R.drawable.img25,
        26 to R.drawable.img26,
    )

    val map: Map<Int, String> = mapOf(
        1 to "\"I am not young enough to know everything.\"",
        2 to "\"The very essence of romance is uncertainty\"",
        3 to "\"The truth is rarely pure and never simple.\"",
        4 to "\"I can resist anything except temptation.\"",
        5 to "\"Life is far too important a thing ever to talk seriously about.\"",
        6 to "\"Life is far too important a thing ever to talk seriously about.\"",
        7 to "\"I can believe anything , provided that it is quite incredible\"",
        8 to "\"Experience is merely the name men give to their mistakes.\"",
        9 to "\"To define is to limit.\"",
        10 to "\"Nothing can cure the soul but the senses, just as nothing can cure the senses but the soul.\"",
        11 to "\"Whenever a man does a thoroughly stupid thing, it is always from the noblest motives.\"",
        12 to "\"A little sincerity is a dangerous thing, and a great deal of it is absolutely fatal.\"",
        13 to "\"I am one of those who are made for exceptions, not for laws.\"",
        14 to "\"I never think of the future - it comes soon enough. …\"",
        15 to "\"Try not to become a man of success, but rather try to become a man of value. \"",
        16 to "\"The true sign of intelligence is not knowledge but imagination.\"",
        17 to "\"I have no special talent. I am only passionately curious.\"",
        18 to "\"Education is what remains after one has forgotten what one has learned in school.\"",
        19 to "\"I am not young enough to know everything.\"",
        20 to "\"Life is like riding a bicycle. To keep your balance, you must keep moving.\"",
        21 to "\"Only two things are infinite, the universe and human stupidity, and I'm not sure about the former.\"",
        22 to "\"Look deep into nature, and then you will understand everything better.\"",
        23 to "\"Only I can change my life. No one can do it for me.\"",
        24 to "\"You will never win if you never begin.\"",
        25 to "\"Life is 10% what happens to you and 90% how you react to it.\"",
        26 to "\"It does not matter how slowly you go as long as you do not stop.\"",
        27 to "\"A friend is someone who gives you total freedom to be yourself.\"",
        28 to "\"If you don't like something, change it. If you can't change it, change your attitude.\"",
        29 to "\"Nothing you wear is more important than your smile.\"",
        30 to "\"Start where you are. Use what you have. Do what you can.\"",
        31 to "\"If you can dream it, you can do it.\"",
        32 to "\"Opportunities are like sunrises. If you wait too long, you miss them.\"",
        33 to "\"The biggest adventure you can take is to live the life of your dreams.\"",
        34 to "\"You have to dream before your dreams can come true.\"",
        35 to "\"When you have a dream, you've got to grab it and never let go.\"",
        36 to "\"First they ignore you, then they laugh at you, then they fight you, then you win.\"",
        37 to "\"Never make a decision when you are upset, sad, jealous or in love.\"",
        38 to "\"There are no strangers here; Only friends you haven't yet met.\"",
        39 to "\"Faith is taking the first step even when you don't see the whole staircase.\"",
        40 to "\"A dream you dream alone is only a dream. A dream you dream together is reality.\"",
        41 to "\"Knowledge will give you power, but character respect.\"",
        42 to "\"When you forgive, you in no way change the past - but you sure do change the future.\"",
        43 to "\"If you're going through hell, keep going.\"",
        44 to "\"Age is a case of mind over matter. If you don't mind, it don't matter.\"",
        45 to "\"What you do today can improve all your tomorrows.\"",
        46 to "\"Sometimes it's the journey that teaches you a lot about your destination.\"",
        47 to "\"Either you run the day or the day runs you.\"",
        48 to "\"Believe you can and you're halfway there.\"",
        49 to "\"The most beautiful thing you can wear is confidence.\"",
        50 to "\"No matter what people tell you, words and ideas can change the world.\"",
        51 to "\"You are never too old to set another goal or to dream a new dream.\"",
        52 to "\"You cannot escape the responsibility of tomorrow by evading it today.\"",
        53 to "\"A true friend never gets in your way unless you happen to be going down.\"",
        54 to "\"Ambition is the path to success. Persistence is the vehicle you arrive in.\"",
        55 to "\"Nobody cares how much you know, until they know how much you care.\"",
        56 to "\"Passion is energy. Feel the power that comes from focusing on what excites you.\"",
        57 to "\"I do believe that if you haven't learnt about sadness, you cannot appreciate happiness.\"",
        58 to "\"No matter how busy you are, you must take time to make the other person feel important.\"",
        59 to "\"By failing to prepare, you are preparing to fail. Benjamin Frankling.\"",
        60 to "\"If you are not too long, I will wait here for you all my life.\"",
        61 to "\"Logic will get you from A to B. Imagination will take you everywhere.\"",
        62 to "\"Beauty is how you feel inside, and it reflects in your eyes. It is not something physical.\"",
        63 to "\"The beautiful thing about learning is nobody can take it away from you.\"",
        64 to "\"Do not worry about your difficulties in Mathematics. I can assure you mine are still great.\"",
        65 to "\"It is never too late to be what you might have been.\"",
        66 to "\"Kiss me and you will see how important I am.\"",
        67 to "\"If you cannot do great things, do small things in a great way.\"",
        68 to "\"A smile is happiness you'll find right under your nose.\"",
        69 to "\"True knowledge exists in knowing that you know nothing.\"",
        70 to "\"You can't blame gravity for falling in love.\"",
        71 to "\"When you're curious, you find lots of interesting things to do.\"",
        72 to "\"It isn't the mountains ahead to climb that wear you out; it's the pebble in your shoe.\"",
        73 to "\"It takes courage to grow up and become who you really are.\"",
        74 to "\"Price is what you pay. Value is what you get. \"",
        75 to "\"Good things happen when you meet strangers.\"",
        76 to "\"You don't learn to walk by following rules. You learn by doing, and by falling over.\"",
        77 to "\"The way I see it, you should live everyday like its your birthday.\"",
        78 to "\"How old would you be if you didn't know how old you are?\"",
        79 to "\"If you find a path with no obstacles, it probably doesn't lead anywhere.\"",
        80 to "\"You can never quit. Winners never quit, and quitters never win.\"",
        81 to "\"If you are not willing to risk the unusual, you will have to settle for the ordinary.\"",
        82 to "\"Generosity is giving more than you can, and pride is taking less than you need.\"",
        83 to "\"A problem is a chance for you to do your best.\"",
        84 to "\"If you can't feed a hundred people, then feed just one.\"",
        85 to "\"Always laugh when you can. It is cheap medicine.\"",
        86 to "\"Forget the past - the future will give you plenty to worry about.\"",
        87 to "\"In a gentle way, you can shake the world.\"",
        88 to "\"When you arrive at a fork in the road, take it.\"",
        89 to "\"Lose your dreams and you might lose your mind.\"",
        90 to "\"Smile, it is the key that fits the lock of everybody's heart.\"",
        91 to "\"Peace begins with a smile.\"",
        92 to "\"Smile, it's free therapy.\"",
        93 to "\"A smile is the universal welcome.\"",
        94 to "\"Smile at a stranger. See what happens.\"",
        95 to "\"If you force yourself to smile, within a couple minutes, you feel happy.\"",
        96 to "\"Change your life today. Don't gamble on the future, act now, without delay.\"",
        97 to "\"There are two great days in a person's life - the day we are born and the day we discover why.\"",
        98 to "\"With the past, I have nothing to do; nor with the future. I live now.\"",
        99 to "\"Luck is great, but most of life is hard work.\"",
        100 to "The only disability in life is a bad attitude.",
        101 to "Netflix and chill.",
        102 to "Sorry not sorry",
        103 to "Swerve",
        104 to "The struggle is real",
        105 to "Goals AF",
        106 to "On fleek",
        107 to "Clap back",
        108 to "Ratchet",
        109 to "I can’t even",
        110 to "JOMO",
        111 to "Humble brag",
        112 to "Break the Internet",
        113 to "Bye Felicia",
        114 to "Pics or it didn’t happen",
        115 to "FOH",
        116 to "Said no one ever",
        117 to "Because duh",
        118 to "YAAAAAS",
        119 to "Adulting",
        120 to "Savage",
        121 to "Suh",
        122 to "Shade",
        123 to "Woke",
        124 to "Trollin",
        125 to "Bounce",
        126 to "Bae",
        127 to "Rad",
        128 to "Rents",
        129 to "Squad",
        130 to "Swol",
        131 to "Chuh",
        132 to "Chill",
        133 to "Amirite",
        134 to "I'm objective; I object to everything.",
        135 to "When there's a will, I want to be in it!",
        136 to "A bank is a place that will lend you money, if you can prove that you don\'t need it.",
        137 to "If I agreed with you, we'd both be wrong.",
        138 to "Some people hear voices.. Some see invisible people.. Others have no imagination whatsoever.",
        139 to "I never forget a face, but in your case I\'ll be glad to make an exception.",
        140 to "I don\'t care what is written about me as long as it isn\'t true.",
        141 to "Respect old people. They graduated school without Google or Wikipedia.",
        142 to "If I won the award for laziness, I would send somebody to pick it up for me.",
        143 to "If Cinderella's shoe fit perfectly, then why did it fall off?",
        144 to "Maybe if we tell people the brain is an app, they'll start using it. ",
        145 to "A cop pulled me over and told me \"Papers\", so I said \"Scissors, I win!\" and drove off. ",
        146 to "My wallet is like an onion, opening it makes me cry. ",
        147 to "If you're hotter than me, then that means I'm cooler than you. ",
        148 to "When nothing is going right, go left. ",
        149 to "Of course I talk to myself... sometimes I need expert advice. ",
        150 to "Dear Math, please grow up and solve your own problems, I'm tired of solving them for you. ",
        151 to "My silence spoke a thousand words, but you never heard them. ",
        152 to "I really should do something with my life... maybe tomorrow. ",
        153 to "Be yourself; everyone else is already taken.",
        154 to "Square box, round pizza, triangle slices, now that\'s confusing.",
        155 to "The only relationship I have is with my Wi-Fi. We have a connection.",
        156 to "I am on a seafood diet. I see food, and I eat it.",
        157 to "The future is shaped by your dreams, so stop wasting time and go to sleep!",
        158 to "A mind is like a parachute. It doesn\'t work if it is not open.",
        159 to "The great pleasure in life is doing what people say you cannot do.",
        160 to "Never ask a starfish for directions. ",
        161 to "Why is Monday so far from Friday, and Friday so close to Monday?",
        162 to "Do you believe in love at first sight, or should I walk by again? ",
        163 to "If lying was a job some people would be billionaires. ",
        164 to "Interviewer: So tell me about yourself. Me: I'd rather not.. I kinda want this job. ",
        165 to "If nothing is impossible is it possible for something to be impossible? -",
        166 to "How does a train eat? Chew, Chew... ",
        167 to "How does the healthy dog bark? Ruff Ruff. How does the cold dog bark ? Scarf Scarf. How does the confused dog bark? Wutf? Wutf? ",
        168 to "You know the speed of light; so what is the speed of dark? ",
        169 to "Could you please be as silent as the G in lasagna? ",
        170 to "Isn't it funny that the number 2 pencil is the most popular?",
        141 to "What's best way to build upper arm strength? Take lots of selfies.",
        142 to "Is it good if a blow dryer blows? ",
        143 to "They say \"don't try this at home\" so I'm coming over to your house to try it.",
        144 to "Alaska: home of Northern Lights",
        145 to "Arkansas: home of America's First Toothbrush",
        146 to "Alabama: First state to rescind a man's right to beat his wife",
        147 to "Arizona: Largest area of Designated Native American Land",
        148 to "California: Avocado Capital of the World",
        149 to "Colorado: first State to legalize marijuana for adults",
        150 to "Connecticut: home of the oldest continuously-published newspaper",
        151 to "Connecticut: home of first hamburger",
        152 to "Connecticut: home first color TV",
        153 to "Delaware: first state to ratify the constitution",
        154 to "Florida: Inventor of Air-Conditioning Technology",
        155 to "Georgia: First state to approve anti-bullying laws",
        156 to "Hawaii: Only USA State that grows coffee",
        157 to "Idaho: The Gem State",
        158 to "Illinois: First State to abolish Slavery",
        159 to "Indiana: Home of over 100 species of trees",
        160 to "Iowa: Highest Literacy Rate",
        161 to "Kansas: Home to the first female mayor",
        162 to "Kentucky: Home of Abe Lincoln",
        163 to "Louisiana: Largest Capital Building in the Country",
        164 to "Maine: Acadia National Park",
        165 to "Maryland: first naval academy",
        166 to "Massachusetts: First State to Issue Marriage License to Same Sex Couples",
        167 to "Michigan: First Rape Shield Law",
        168 to "Minnesota: First Charter School",
        169 to "Mississippi: first lung transplant",
        170 to "Missouri: First state to free its slaves",
        171 to "Montana: First Female Congresswoman",
        172 to "Nebraska: Equlity before the law (State Motto)",
        173 to "Nevada: more mountains than any other State",
        174 to "New Hampshire: \"Live Free or Die\"",
        175 to "New Jersey: Diner Capital of the Country",
        176 to "New Mexico: First Latina Female Governor",
        177 to "New York: known for its diversity",
        178 to "North Carolina: first American (English descendant) birth",
        179 to "North Dakota: most Churches per capita than any State",
        180 to "Ohio: first black Mayor of a Major City",
        181 to "Oklahoma: first state to successfully install a parking meter",
        182 to "Oregon: home of the Painted Hills",
        183 to "Pennsylvania: home to the first computer, built in 1946",
        184 to "Rhode Island: home of oldest library",
        185 to "South Carolina: Largest gingko farm in the World",
        186 to "South Dakota: home of Mount Rushmore",
        187 to "Tennessee: home of Jack Daniels",
        188 to "Texas: home to the Live Music Capital of the World",
        189 to "Utah: home of first department store",
        190 to "Vermont: the only State without billboards",
        191 to "Virginia: first state to apologize for its role in slavery",
        192 to "Washington: birth of the Grunge Movement",
        193 to "West Virginia: home of the Mothman",
        194 to "Wisconsin: home of the first Kindergarten",
        195 to "Wyoming: first State to allow women to vote",
        196 to "Honey never goes off. Not after one year, not after two — never.",
        197 to "The Turritopsis Nutricula jellyfish is the only known organism on Earth which is biologically immortal.",
        198 to "The heart of a blue whale is so massive that a human being can swim through its arteries.",
        199 to "An octopus has three hearts.",
        200 to "Originally, Feng shui was the art of choosing an appropriate place for a grave.",
        201 to "On Saturn and Jupiter, rain is made from diamonds.",
        202 to "There are ten times more bacteria in the human body than there are cells.",
        203 to "Frankenstein was the name of the creator, not the monster.",
        204 to "Oxford University is older than the Aztec Empire.",
        205 to "In Cyprus, Santa Claus is called Basil.",
        206 to "No one has ever managed to tame an African elephant.",
        207 to "A lack of sleep makes people see enemies all around them.",
        208 to "Women’s hearts beat faster, but men’s hearts are larger.",
        209 to "It is reported that in hot weather the Eiffel Tower grows by up to six inches, which would seem to imply that in cold weather it can shrink by up to six inches. ",
        210 to "ELEVEN PLUS TWO is an anagram of TWELVE PLUS ONE",
        211 to "In a room of of 35 people, the probability of at least two people sharing the same birthday is approximately 85%.",
        212 to "There are more ways of arranging a pack of ordinary playing cards than there have been seconds since the universe began.",
        213 to "One cubic centimetre of neutron star material (the size of a sugar cube) has the mass of approximately one billion (1000,000,000) elephants.",
        214 to "A black hole the size of a baseball has a mass approximately 5 times that of Earth.",
        215 to "After each players has made 3 moves in a game of chess, the peices could form any one of over 9 million different positions.",
        216 to "Half of the human genome is identical to that of the banana.",
        217 to "If all the blood vessels in the adult human body were laid end to end they would stretch to approximately 160,000 kilometres.",
        218 to "Euclid proved that there are an infinite number of prime numbers.",
        219 to "The largest known prime number has more than four million digits.",
        220 to "Albert Einstein was 26 when he published his Special Theory of Relativity.",
        221 to "Lemons contain more sugar than strawberries.",
        222 to "Japan is the largest exporter of frogs' legs in the world.",
        223 to "The average person speaks about 31, 500 words a day.",
        224 to "It is impossible to lick your elbow.",
        225 to "111111111 x 111111111 = 12345678987654321",
        226 to "Scientists calculate the age of the Earth to be approximately 4.54 billion years ",
        227 to "The age of the Universe is estimated to be 13.75 billion years.",
        228 to "In 1969 George Perec wrote La Disparition (The Dissappearance), a 300 page novel which does not contain the letter e. ",
        229 to "A male honeybee (called a drone) has a grandfather but no father.",
        230 to "Honeybees cannot see the colour red.",
        231 to "Honeybees have five Eyes: two large compound eyes and three smaller ocelli eyes.",
        232 to "Male honeybees (drones) die in the process of mating.",
        233 to "Male honeybees (drones) do not sting",
        234 to "Queen bumblebees eat their own grandchildren. ",
        235 to "The most commonly used letter in Russian is O.",
        236 to "The Earth gains appoximately 40,000 tonnes in mass each year due to dust falling from space.",
        237 to "Warmer water can sometimes freeze faster than colder water. This is know as the Mpemba effect.",
        238 to "The kiwi of New Zealand is the only wingless bird in the world.",
        239 to "There are 28,829 unique word forms in Shakespeare's works.",
        240 to "In Chinese, the word “ma” can mean “mother”, “hemp” or “horse” depending on whether it is spoken in a high, medium or low pitch.",
        241 to "Large tropical species of carnivorous plants are able to trap and digest frogs, birds and small mammals.",
        242 to "Onions have about 5 times more DNA than humans.",
        243 to "The salamander has about 26 times more DNA than humans.",
        244 to "Male Jack Jumper ants have only 1 chromosome.",
        245 to "When dung beetles get lost, they can navigate their way home by looking at the Milky Way.",
        246 to "Fireflies are beetles not flies.",
        247 to "Peanuts are not nuts. They are legumes.",
        248 to "In 2012, the richest 0.1% of US families had the same net wealth as the bottom 90%",
        249 to "The sum of all the numbers on a roulette wheel is 666.",
        250 to "If Michael Phelps were a country, he'd ranke No. 35 on the aal-time olimpic gold medalist list, ahead of 97 .",
        251 to "Wilt Chamberlain didn't win MVP the year he scored 50.4 points and grabbed 22.9 rebounds per game, (Bill Russell did).",
        252 to "The average golf ball has 336 dimples.",
        253 to "In the 1970's Jack Niclaus played all 40 majors and made the top 10 en 35.",
        254 to "Babe Ruth only won four world series in 15 seasons with the New York Yankees.",
        255 to "Yogu Berra won 13 word series in 18 seasons with the Yanks.",
        256 to "Only 10 other Quaterbacks in NFL history have thrown half as many touchdown passes as Peyton Manning.",
        257 to " Bill Buckner had more hits that Ted Williams.",
        258 to "The longest average NFL careers. Punters, at 4,87 years.",
        259 to "At the first modern Olimpics, winers were awarded silver medals.",
        260 to "Roger Maris never, intentionally, walked the year he hit 61 homeruns.",
        261 to "China did not win an olimpic medal until 1984, at the Beijing games, the Chiniese won 100.",
        262 to " The men's long jump world record has been broken once since 1969.",
        263 to "Greece is the only country to have participated in every olympics under its own flag.",
        264 to "Grant Hill's mother roomed with Hillary Clinton at Wellesley. ",
        265 to "Starting in 1990, Michael Jordan and The Chicago Bulls never had a three-game losing streak for eight years.",
        266 to "From 1918 to 1949, The Philadelphia Phillies had one winning season.",
        267 to "Secretariat's 31-length win at the 1973 Belmont Stakes is two seconds faster than any other horse ever to run the race.",
        268 to " Wil Chamberlain won three-straight big eight titles in high jump and was also inducted into the Volleyball Hall of Fame.",
        269 to "Michael Jordan's nickname in high school was Magic, after Magic Johnson. ",
        270 to "Joe Gibbs is the only coach to win the Super Bowl with three different quarterbacks.",
        241 to "Spitting into your hand before picking up the bat is said to bring good luck.",
        242 to "A wad of gum stuck on a player's hat brings good luck.",
        243 to "It is bad luck if a dog walks across the diamond before the first pitch.",
        244 to "It is good luck to step on one of the bases before running off the field at the end of an inning.",
        245 to "It is bad luck to touch the baselines while running off and onto the field between innings.",
        246 to "Lending a bat to a fellow player is a serious jinx.",
        247 to "Some players actually sleep with their bat to break out of a hitting slump or stay in a groove.",
        248 to "If a pitcher is throwing a perfect game or a no-hitter, never speak of it while it's going on.",
        249 to "The last person to shoot a basket during the warm-up will have a good game.",
        250 to "Wipe the soles of your sneakers for good luck.",
        251 to "Bounce the ball before taking a foul shot for good luck.",
        252 to "The number 300, a perfect score, on your license plate will increase your bowling score.",
        253 to "Carry charms on your bowling bag, in your pockets, or around your neck for good luck",
        254 to "Fish may not bite if a barefoot woman passes you on the way to the dock.",
        255 to "Spit on your bait before casting your rod to make fish bite.",
        256 to "Throw back your first catch for good luck.",
        257 to "It is bad luck to change rods while fishing.",
        258 to "Don't tell anyone how many fish you've caught until you're done or you won't catch another.",
        259 to "Double numbers on a football player's uniform brings good luck.",
        260 to "It's bad luck for a professional football player to take a new number when he is traded to another team.",
        261 to "A mascot is an important good luck symbol.",
        262 to "When playing golf, start with odd-numbered clubs for good luck.",
        263 to "In golf, balls with a number higher than 4 are bad luck.",
        264 to "When playing golf, carry coins in your pockets for good luck.",
        265 to "It is bad luck for hockey sticks to lie crossed.",
        266 to "It is bad luck to say âshutuotâ in the locker room before a hockey game.",
        267 to "Hockey players believe they'll win the game if they tap the goalie on his shin pads before a game.",
        268 to "When playing tennis, It's bad luck to hold more than two balls at a time when serving.",
        269 to "When playing tennis, avoid wearing the color yellow.",
        270 to "When playing tennis, walk around the outside of the court when switching sides for good luck.",
        271 to "In baseball, When you spit, you must kick It.",
        272 to "Michael Jordan would always wear his UNC shorts under his NBA shorts.",
        273 to "Serena Williams will not change her socks once during a tournament",
        274 to "Brian Urlacher eats two chocolate chip cookies before every game",
        275 to "Jerry Tarkanian had to chew on a towel during games",
        276 to "Jason Terry wears the shorts of his opponents on nights before games",
        277 to "Some people believe hanging a horseshoe in the bedroom or on a door knob with its ends pointing upwards will bring good luck ",
        278 to "Cherry was the fruit that appeared on the first screen in the original \"Pac-Man\" arcade game.",
        279 to "Pennyworth what the last name of Bruce Wayne/Batman's butler Alfred.",
        280 to "Jughead Jones, an Archie character, wore a crown beanie and loved hamburgers.",
        281 to "On what part of your body would you wear \"mules\"?...Feet",
        282 to "What is the name of the face used by the humor magazine \"MAD\" as mascot and icon?...Alfred E. Neuman",
        283 to "What symbol is used for the category \"live theatre\" on the Hollywood Walk of Fame?...Twin masks",
        284 to "If you were in a car or truck with a CB radio and you heard \"Smokey at 15,\" what would that mean?...State police at mile marker/exit 15.",
        285 to "In toys, TV and movies, what are Autobots and Decepticons?...Transformers",
        286 to "To which type of leisure activity does the term \"cruciverbalism\" refer?...crosswords",
        287 to "What iconic object does Taylor discover at the end of the original \"Planet of the Apes\" movie?...Statue of Liberty",
        288 to "Which actor played the role of Harry Tasker in the movie \"True Lies\"?...Arnold Schwarzenegger",
        289 to "On which 1963 film is \"Chicken Run\" based?...The Great Escape",
        290 to "What character, created by David Morrell, is the movie \"First Blood\" centered around?...John Rambo",
        291 to "What was the name of the movie released in 1987, that ran for a staggering 5,220 minutes (87 hrs)?...The Cure For Insomnia",
        292 to "Which actor played Robert Langdon in \"The Da Vinci Code\" (2005) and \"Angels and Demons\" (2009)?...Tom Hanks",
        293 to "Who played a swashbuckling pirate in \"Captain Blood\" (1935) and \"The Sea Hawk\"(1940)?...Errol Flynn",
        294 to "For what film did Frank Sinatra win an Academy Award for Best Supporting Actor?...For what film did Frank Sinatra win an Academy Award for Best Supporting Actor?",
        295 to "What supernatural movie comedy features the line 'He slimed me'?...Ghostbusters",
        296 to "Who played Scrooge in the movie \"The Muppet Christmas Carol\"?...Michael Caine",
        297 to "In 'Snow White and the Seven Dwarfs' what did the seven dwarfs do for a job?...Miners",
        298 to "Who directed the movie \"Charlie and the Chocolate Factory\" (2005)?...Tim Burton",
        299 to "Which state did Forrest Gump call home?...Alabama",
        300 to "Who was James Dean's leading lady in \"Rebel Without a Cause\"?...Natalie Wood",
        301 to "What kind of vehicle was featured in a 2008 Clint Eastwood movie of the same name?...Gran Torino",
        302 to "What is Indiana Jones' real first name?...Henry",
        303 to "Roy Rogers: what was the name of his dog?...Bullet",
        304 to "Which member of Destiny's Child had number one UK hits with,'If I Were a Boy' and 'Crazy in Love'?... Beyoncé Knowles",
        305 to "Which major recording artist had the nickname of \"the man in black\"?...Johnny Cash",
        306 to "Which band gave the advice to \"fight for your right to party\"?...Beastie Boys",
        307 to "Who wrote \"The Barber of Seville\"?...Gioachino Rossini",
        308 to "John Lennon wrote the beautifully haunting song \"Julia\" about whom?...His mother",
        309 to "Which of Shakespeare's plays is Taylor Swift's song \"Love Story\" about?...Romeo and Juliet",
        310 to "Which deceased movie star was mentioned in the song \"Rock On\" by David Essex in 1973?...James Dean",
        311 to "Nena had a US number 2 hit with \"Luftballons\" in 1989. What nationality is she?...German",
        312 to "The Bee Gees had a younger brother who occasionally toured with them. What was his name?...Andy Gibb",
        313 to "What is the name of the band that periodically tours with Bruce Springsteen?... E Street Band",
        314 to "What \"hefty\" jazz pianist, organist, composer and entertainer was born in 1904?...Fats Waller",
        315 to "What is the full birth name of Boy George?...George Alan O'Dowd",
        316 to "In a song performed by Three Dog Night, which number is \"the loneliest number that you'll ever do\"?...One",
        317 to "Which singer had a hit with the song \"Oliver's Army\" in 1979?...Elvis Costello",
        318 to "Where did British group, 10CC, have a 'Dreadlock Holiday' in 1978?...Jamaica",
        319 to "The rapper Eminem (Marshall Mathers) also goes by another name. What is it?...Slim Shady",
        320 to "What Canadian band could be classified as \"catastrophically in fashion\" ?...Tragically Hip",
        321 to "Which American group had hits with \"I Get Around\", California Girls\" and \"Good Vibrations\"?....The Beach Boys",
        322 to "In the world of tennis, why wasn't Wimbledon held between 1940 and 1945?...World War II",
        323 to "What two gymnastic events are done in competition by both men and women?...Vault and Floor",
        324 to "Which west African country's official motto is \"The love of liberty brought us here\"?...Liberia",
        325 to "Where is the meridian line in London?...Greenwich",
        326 to "What state, with a capital of Lincoln, is also known as the Cornhusker state?...Nebraska",
        327 to "Olympia is the capital of what state whose university's nickname is the Huskies?...Washington",
        328 to "In which ocean would you find the island of Guam?...Pacific Ocean",
        329 to "How did the capital city of New Zealand, Wellington, get the nickname \"Wellywood\"?...It is the centre of the New Zealand film industry.",
        330 to "n which country would you find a rabbit-proof fence over 2000 miles (or over 3,200 km) long?...Australia",
        331 to "Which country, that was once known as Ceylon, has also been referred to as 'Zeilan'?...Sri Lanka",
        332 to "Which country in Europe is also known as 'The Boot'?...Italy",
        333 to "Who is in charge of maintaining the Mississippi River and preventing flooding?...US Army Corps of Engineers",
        334 to "North and South America are joined together by what isthmus?...Isthmus of Panama",
        335 to "What mnemonic device helps one to remember the five Great Lakes of Canada and the U.S.?...HOMES (Huron, Ontario, Michigan, Erie, and Superior)",
        336 to "What is the national flower of Holland and Hungary?...The Tulip",
        337 to "What U.S. state has been called \"The Grand Canyon State\"?...Arizona",
        338 to "Topeka is the capital of which \"jayhawk\" state\"?...Kansas",
        339 to "Of which African country is Maseru the capital?...Lesotho",
        340 to "What is the Earth's largest island, that is not also a continent?...Greenland",
        341 to "Which region of Scotland has the same name as a musical instrument?...Fife",
        342 to "What is the name given to the spot in Massachusetts where the Pilgrims are said to have landed?...Plymouth Rock",
        343 to "Often found on the floors of Roman villas, what are tesserae?...Mosaic tiles",
        344 to "The civil war of which country lasted from 1936-1939?...Spain",
        345 to "Two German chancellors in sequence both had the first name Helmut. What were their surnames?...Schmidt and Kohl",
        346 to "Who was the queen of Spain when the decree was published in 1492 to expel the Jews?...Isabella I of Castille",
        347 to "What was the relaxing of tensions during the mid Cold War called?...Detente",
        348 to "In which European city was Checkpoint Charlie?...Charlie",
        349 to "Which country did Sukarno help lead to independence in 1945, becoming its first President?...Indonesia",
        350 to "In ancient Sparta, what was a helot?...Slave",
        351 to "Which country is the republican political party, Sinn Féin, associated with?...Ireland",
        352 to "Launched in 1973, what was the first space station owned and operated by NASA?...Skylab",
        353 to "According to legend, what did Archimedes have in common with Lady Godiva?...Both famously went nude in public.",
        354 to "What law enforcement agency can be traced to the 8th Texas Cavalry Regiment?...Texas Rangers",
        355 to "By which name was the American World War 2 Medium tank 'M4' better known?...Sherman",
        356 to "What branch of the British armed forces was formed on 1 April 1918?...Royal Air Force",
        357 to "What prominent Greek orator overcame a speech handicap by putting stones in his mouth?...Demosthenes",
        358 to "Ancient Romans created something that would help make large buildings. What was this achievement?...Concrete",
        359 to "In which war was the Avro-Lancaster bomber plane used?...World War II",
        360 to "What grand-nephew of Julius Caesar was the first emperor of Rome?...Augustus",
        361 to "Which religious leader is said to have found enlightenment while sitting under a tree?...Buddha",
        362 to "What is the Society of Friends, or Friends of the Truth, more commonly known as?...Quakers",
        363 to "Which day of the week do Seventh-Day Adventists observe as the Sabbath day?...Saturday",
        364 to "According to the Roman Catholic Church, what is a Marian apparition?...A vision of the Virgin Mary",
        365 to "What toy is associated with the Jewish celebration of Hanukkah?...Dreidel",
        366 to "A mosque is associated with which religion?...Islam",
        367 to "If you exhibit wounds that correspond to the wounds of Christ, precisely what are you experiencing?...Stigmata",
        368 to "In the King James Version Bible, what nationality was Goliath?...Philistine",
        369 to "What is the name shared by a country music singer and a MLB player, who pitched a perfect game?...Kenny Rogers",
        370 to "For which Sweden-born actress/singer did Elvis Presley purchase a round, hot pink bed as a gift?...Ann-Margret",
        341 to "Which Academy award winning actress starred in \"Howards End,\" \"Junior,\" and \"Nanny McPhee?\"...Emma Thompson",
        342 to "Which member of the Beatles died first?...John",
        343 to "What \"fruity\" Hollywood actress was nicknamed \"The Brazilian Bombshell\"?...Carmen Miranda",
        344 to "What Saturday Night Live regular was murdered by his wife who subsequently killed herself?...Phil Hartman",
        345 to "What is the given name of the wrestler/actor known as \"The Rock\"?...Dwayne Johnson",
        346 to "How did Sonny Bono die?...Skiing accident",
        347 to "Pop music icon Michael Jackson passed away in what city in 2009?...Los Angeles",
        348 to "Which Oscar-nominated star of \"Born on the Fourth of July\" was actually born on the third of July?...Tom Cruise",
        349 to "Who is Ralph Lifshitz also known as?...Ralph Lauren",
        350 to "What was the nickname of the silver-screen singing cowboy and father to the late actor John Ritter?...Tex",
        351 to "Actor David Carradine passed away in what country, where he was making a movie?...Thailand",
        352 to "Who was Dame Margot Fonteyn's Russian ballet partner?...Rudolf Nureyev",
        353 to "In the UK, what is a lollipop man or lady?...School crossing patrol officer",
        354 to "Sharing its name with a type of wind, what Boeing helicopter is technically known as the CH-47?...Chinook",
        355 to "Sometimes used to indicate weight, an octothorpe is also known as ....?...Number, Hash or Pound Sign (#)",
        356 to "Dot dot dot, dash dash dash, dot dot dot?...SOS",
        357 to "What is a cardinal tetra?...A small freshwater fish",
        358 to "What liquid is found in most cigarette lighters?...Butane",
        359 to "What is the common definition for the Mafia code of honor term \"Omerta\"?...Code of silence",
        360 to "What is the dot of an i or j called?...Tittle",
        361 to "According to legend, which plant screams when the root is dug up?...Mandrake",
        362 to "What does Volkswagen, the popular German car, mean in English?...people's car",
        363 to "What company logo, featured in the movie \"Cast Away\", contains an arrow between two of the letters?...FedEx",
        364 to "Leo the Lion was the mascot for which film studio?...MGM",
        365 to "In what month is the official first day of summer in the Northern Hemisphere?...June",
        366 to "In the famous painting, \"American Gothic\", what is the man in the picture holding?...pitchfork",
        367 to "If something is described as being antediluvian, what is it?...Very old",
        368 to "You're visiting Australia and someone calls you \"cobber\". What did he call you?...Mate",
        369 to "Which Greek philosopher was the mentor of Plato?...Socrates",
        370 to "In Greek mythology, what would happen if you looked at Medusa?...You turned to stone",
        371 to "What does a phrenologist study?...Bumps on the head",
        372 to "Which Broadway musical's plot is centered around the auditions for a Broadway musical?...A Chorus line",
        373 to "What does a cooper make?...Barrels",
        374 to "The word\"smog\" comes from what?...Smoke + fog",
        375 to "In the Arthurian legend, where did King Arthur live?...Camelot",
        376 to "What art medium was the early 20th century artist Louis Comfort Tiffany best known for?...Stained glass",
        377 to "In Roman mythology who was goddess of the dawn?...Aurora",
        378 to "Which airline's logo features a white kangaroo on a red background?...Qantas",
        379 to "In 2007 a British teacher working in Sudan was arrested for naming the class teddy bear what?...Mohammed",
        380 to "Which manufacturer of dental care products claims to be \"the brand more dentists use\"?...Oral-B",
        381 to "Which famous school is located in the neighbourhood of Windsor Castle?...Eton College",
        382 to "The construction of the Eiffel Tower celebrated which historical event?...The centennial of the French Revolution",
        383 to "Which French leader ushered in the French Fifth Republic?...Charles de Gaulle",
        384 to "Which world statesman and national hero was formerly known as Prisoner 46664?...Nelson Mandela",
        385 to "What is the longest line of constant latitude of the Earth?...Equator",
        386 to "Which international organization has won the Nobel Peace Prize the most often?...International Red Cross",
        387 to "What US president, commonly known by his initials, was elected to office for a record 4 terms?...Franklin Delano Roosevelt",
        388 to "Who was the first British Prime Minister?...Sir Robert Walpole",
        389 to "Many people drive MG cars, but what does the MG logo stand for?...Morris Garages",
        390 to "Who was known for asking readers to \"believe it or not\"?...Robert Ripley",
        391 to "What was the \"attention getting\" title of plane crash survivor Helen Klaben's book in 1963?...Hey, I'm Alive!",
        392 to "Who is credited with inventing the world's first working, publicly demonstrated television?...John Logie Baird",
        393 to "Which city did the infamous Jack the Ripper roam?...London",
        394 to "Henry VII married Elizabeth of York in 1486. Who was their most famous offspring?...King Henry VIII",
        395 to "Who was the first Pole to become a Pope?...Karol Wojtyla",
        396 to "Of which famous Scottish poet was the 250th anniversary of his birth celebrated in January 2009?...Robert Burns",
        397 to "Who said \"The maxim of the British people is 'Business As Usual'\"?...Winston Churchill",
        398 to "Who said \"Think! How the hell are you gonna think and hit at the same time?\"...Yogi Berra",
        399 to "Henry the VIII had six wives. How many of them were named Anne?...Two",
        400 to "What did an Irishman called Thomas Blood try to do that made him famous in 1671?...Steal the English Crown jewels",
        401 to "Which architect designed the Royal Observatory, Greenwich?...Sir Christopher Wren",
        402 to "What does a fletcher make?...Arrows",
        403 to "Which stone can float on water?...Pumice",
        404 to "What is the term used to describe the number of protons an element possesses?...Atomic number",
        405 to "What charge does a proton have?...Positive",
        406 to "Which is the fastest moving planet in our Solar System?...Mercury",
        407 to "What is the proper name for your belly-button?...Umbilicus",
        408 to "What does 'E' represent in E=MC2?...Energy",
        409 to "Where in the body would you find the pituitary gland?...AT the base of the brain",
        410 to "What is another name for the perimeter of a circle?...Circumference",
        411 to "What constellation is sometimes referred to as 'the archer'?...Sagittarius",
        412 to "What is anaphylactic shock?...Allergic reaction",
        413 to "Where in your body is the deltoid muscle situated?...Shoulder",
        414 to "In the visible light spectrum what color appears between yellow and blue?...Green",
        415 to "What does 20/20 or 6/6 vision actually mean?...Average vision at 20 feet or 6 metres",
        416 to "Which planet in our solar system is also known as the morning star?...Venus",
        417 to "What type of energy production is the focus of photovoltaic science and engineering?...Solar",
        418 to "In which country was the quiz show \"Who Wants to Be a Millionaire?\" first aired?...Great Britain",
        419 to "Which actor plays the former detective Adrian Monk in the TV series 'Monk'?...Tony Shalhoub",
        420 to "Hello, Newman. This is said with great ire in what television show?..Seinfeld",
        421 to "Who was the captain of the Enterprise in the series \"Star Trek?\"..Kirk",
        422 to "Who hosted \"America's Next Top Model?\"…Tyra Banks",
        423 to "Wednesday Addams, from \"The Addams Family\", was related to Gomez Addams in what way?...Daughter",
        424 to "Which television series uses the tag line \"Everyone has a little dirty laundry\"?...Desperate Housewives",
        425 to "Cheers was a sitcom set in what type of location?...A bar",
        426 to "Which detective/lawyer TV show starred Andy Griffith?...Matlock",
        427 to "Nanu, nanu. What actor said this in a television show?...Robin Williams",
        428 to "On which television show do the characters work at Dunder Mifflin Paper Company, Inc.?...The office",
        429 to "Which TV show used a \"Cone of Silence\" to great comic effect?...Get smart",
        430 to "What cartoon had the main characters of Fred, Barney, Wilma and Betty?...The Flintstones",
        431 to "Which TV series featured Betty Suarez, Amanda Tanen and Marc St. James working at MODE?...Ugly Betty",
        432 to "In chess, which two pieces are only allowed to move one space, except in special circumstances?...King and Pawn",
        433 to "What colour is the spice paprika?...Red",
        434 to "What Asian city-state essentially made all types of chewing gum illegal in the 1990s?...Singapore",
        435 to "What is crème anglaise?...Custard",
        436 to "What is reputed to be the best potable remedy for a burning mouth due to eating hot or spicy foods?...Milk",
        437 to "What substance, naturally occurring in some fruits, makes jam set?...Pectin",
        438 to "The name of which French dessert translates to 'white eat'?...blancmange",
        439 to "You ordered your bagel with a \"shmear\". What's on it?...Cream chees",
        440 to "What do you need to play a game of \"craps\"?...A pair of dice",
        441 to "What is the proper name for what is commonly called \"bow-tie pasta\"?...Farfalle",
        442 to "What did Coca-Cola originally contain?...Cocaine",
        443 to "What brand of chocolates was named after a legendary naked lady who rode on a horse?...Godiva",
        444 to "What would you keep in a humidor?...Tobacco",
        445 to "Why don't polar bears eat penguins?...They live in opposite hemispheres",
        446 to "Which animals use baleen instead of teeth as part of their feeding process?...Blue whales",
        447 to "What breed of dog is named for a set of islands off the coast of Scotland?...Shetland Sheepdog",
        448 to "What is herpetology the study of?...Reptiles and amphibians",
        449 to "Is the Tasmanian Devil living, extinct, mythological or a folk tale?...Living",
        450 to "What kind of animal is an addax?...Antelope",
        451 to "When speaking of dogs, what exactly is a mutt?...Mixed breed",
        452 to "What animal known for its colorful face and rump is the world's largest species of monkey?...Mandrill",
        453 to "Which color eyes will you not find in cats?...Purple",
        454 to "Why are rats always chewing things?...They need to wear down their teeth, which never stop growing.",
        455 to "The Iditarod is a dog sled race held in which US State?...Alaska",
        456 to "What is a chiffchaff?...Bird",
        457 to "The narwhal is one of only two species in the Monodontidae family. What is it?...Whale",
        458 to "What colour is an octopus' blood? (when it's oxygenated)…Blue",
        459 to "Which bird is said to hide its head in the sand when in danger?...Ostrich",
        460 to "Is the dodo living, extinct, mythological or a folk tale?...Extinct",
        461 to "Which actor appeared in American Graffiti before starring in Star Wars?...Harrison Ford",
        462 to "Which actress claims she cried when she was shown her wardrobe for the role of the monarch in the 2006 film The Queen?...Helen Mirren",
        463 to "Which agnsty actress was the first American to win a Caésar, the French equivalent Oscar, in 2015?...Kristen Stewart ",
        464 to "BB-8 is an astromech droid from what film?...Star Wars",
        465 to "In the movie \"The Wizard of Oz\", what did the Scarecrow want from the wizard?...Brain",
        466 to "In what year was the original \"Jurassic Park\" film released?...1993",
        467 to "What is the name of the dog from \"Wizard of Oz\"?...Toto",
        468 to "Who does the voice over for Dory from \"Finding Nemo\" and \"Finding Dory\"?...Ellen Degeneres ",
        469 to "The title role of the 1900's movie, \"Pretty Woma\", was played by which actress?...Julia Roberts ",
        470 to "What fictional planet is the superhero, \"Superman\", from?...Krypton ",
        441 to "What fictional city is the home of Batman?...Gotham City ",
        442 to "What \"Alice in Wonderland\" character shouted, \"off with his head!\"?...Queen of Hearts ",
        443 to "What school does Harry Potter attend?...Hogwarts ",
        444 to "What was Marilyn Monroe's name at birth?...Norma Jeane Mortenson ",
        445 to "What was the name of the whale in the 1993 movie, \"Free Willy\"?...Keiko",
        446 to "Who played Dracula in the 1931 vampire-horror film \"Dracula\"?...Bela Lugosi",
        447 to "What popular movie musical, directed by John Hutson, was released in 1982?...Annie",
        448 to "What was the name of the monkey in the Disney movie \"Aladdin\"?...Abu",
        449 to "Who played the fictional anti hero Deadpool in the 2016 movie?...Ryan Reynolds",
        450 to "Which actor played the main character in the 1990 film \"Edward Scissorhands\"?...Johnny Depp",
        451 to "What movie did Elvis Presley first appear in?...Love Me Tender",
        452 to "What is the only mythological animal mentioned in a Harry Potter book title?...Phoenix",
        453 to "What big-headed supervillain voiced by Will Ferrell finds life empty without a hero to fight?...Megamind",
        454 to "In the film classic Star Wars, what was the name of the ancient spaceship captained by Han Solo?...The Millennium Falcon",
        455 to "In a movie title Elvis Presley said Viva to where?...Las Vegas",
        456 to "In the Superman movies what newspaper does Clark Kent Work for?...The Daily Planet",
        457 to "The Wicked Queen gives Snow White what to render her comatose?...An Apple",
        458 to "Which horror movie character is a serial killer possessing a doll? Chucky",
        459 to "In what movie, if you watch a certain video you'll die in 7 days?...The Ring",
        460 to "Which character killed people in their dreams?...Freddy Krueger",
        461 to "Who plays fat Amy in the movie 'Pitch Perfect'?...Rebel Wilson",
        462 to "What \"Star Wars\" actress had an early role in the movie \"Leon: The Professional\"?...Natalie Portman",
        463 to "In 'The Lord Of The Rings', what's the name of the Elf that takes part in The Fellowship Of The Ring?...Legolas",
        464 to "In the 'Harry Potter' movies, Severus Snape and Draco Malfoy were members of which house at Hogwarts?...Slytherin",
        465 to "Which is Angelina Jolie's first and least discussed film?...Cyborg 2",
        466 to "What color were the slippers in the original Wizard of Oz?...Silver",
        467 to "Who was the first woman monster to appear in a movie?...The Bride of Frankenstein",
        468 to "In the movie Mean Girls, where is Caty originally from?...Africa",
        469 to "Who Played the lead in The Last Boy Scout?...Bruce Willis",
        470 to "In the Lion King, what was Simba's fathers name?...Mufasa",
        471 to "In what year was the first Harry Potter movie released?...2001",
        472 to "Ulysses S. Grant appears on the front of which denomination of US. Currency…$50 bill",
        473 to "What is the full name of Australian boyband 5SOS?...5 Seconds of Summer",
        474 to "Which U.S. president appears on the front of the $2 bill?...Thomas Jefferson",
        475 to "Which U.S. state has the longest coastline?...Alaska",
        476 to "What is the capital city of the U.S. state of Hawaii?...Honolulu",
        477 to "What is the tallest mountain in Africa?...Mount Kilimanjaro ",
        478 to "What US state is famous for their juicy peaches?...Georgia"
        )


}